.MODEL SMALL

.STACK 100H

.DATA

; declare variables here

; Common constants

MAX_INMATES DB 10
MAX_INCIDENTS DB 10

TEN DW 10
DAYS_IN_MONTH DW 30
DAYS_IN_YEAR DW 360

; COMMON ARRAYS FOR FEATURES 1 TO 6

INMATE_IDS DW 10 DUP(?)
AGE DW 10 DUP(?)

DURATION_DAY DW 10 DUP(?)
DURATION_MONTH DW 10 DUP(?)
DURATION_YEAR DW 10 DUP(?)

SENTENCE_DAYS DW 10 DUP(?)

INTAKE_DAY DW 10 DUP(?)
INTAKE_MONTH DW 10 DUP(?)
INTAKE_YEAR DW 10 DUP(?)

RELEASE_DAY DW 10 DUP(?)
RELEASE_MONTH DW 10 DUP(?)
RELEASE_YEAR DW 10 DUP(?)

NAMES DB 200 DUP(?)
NAMELEN DB 10 DUP(?)

CRIMES DB 150 DUP(?)
CRIMELEN DB 10 DUP(?)

TOTAL_INCIDENTS DB 10 DUP(0)
RECENT_INCIDENT DB 10 DUP(0)

; FEATURE 3 AND 6 ARRAYS

INMATE_BLOCK DB 10 DUP(0)
BLOCK_OCCUPANCY DB 3 DUP(0)
BLOCK_CAPACITY DB 3,3,4

; INCIDENT HISTORY ARRAYS

INCIDENT_TOTAL DB 0
INCIDENT_INMATE_INDEX DB 10 DUP(?)
INCIDENT_TYPE DB 10 DUP(?)
INCIDENT_PENALTY DW 10 DUP(?)
INCIDENT_NOTES DB 310 DUP('$')

PENALTY_DAYS DW 15, 30, 60, 10

; Common Variables

COUNT DB 0
CURRENT DB 0
TEMP_ID DW ?

SEARCH_ID DW ?
FOUND_INDEX DW ?
FOUND_FLAG DB ?

INPUT_ERR DB ?
NUM_DIGITS DB ?

MAX_TEMP DB ?
STR_LEN_TEMP DB ?

EXTRA_YEAR DW ?
EXTRA_MONTH DW ?

FOUND DB ?
REMAINING DB ?
INMATE_NO DB ?

MOD_DAY DW ?
MOD_MONTH DW ?
MOD_YEAR DW ?

CHOSEN_TYPE DB ?
PENALTY_TEMP DW ?

CURRENT_INPUT_DAY DW ?
CURRENT_INPUT_MONTH DW ?
CURRENT_INPUT_YEAR DW ?

SERVED_DAY DW ?
SERVED_MONTH DW ?
SERVED_YEAR DW ?

REQUIRED_DAY DW ?
REQUIRED_MONTH DW ?
REQUIRED_YEAR DW ?

ELIGIBLE_COUNT DB 0
DATE_FLAG DB 0

BLOCK_TEMP DB ?
OLD_BLOCK_TEMP DB ?
DEST_BLOCK_TEMP DB ?

TEMP_DAY DW ?
TEMP_MONTH DW ?
TEMP_YEAR DW ?

; MENU MESSAGES

MSG_MAIN_MENU DB 0DH,0AH,0DH,0AH,'--- PRISON & INMATE RECORD MANAGEMENT SYSTEM ---',0DH,0AH
DB '1. INMATE INTAKE AND PROFILE CREATION',0DH,0AH
DB '2. SENTENCE TRACKING AND RELEASE DATE CALCULATION',0DH,0AH
DB '3. CELL BLOCK ASSIGNMENT AND OCCUPANCY MANAGEMENT',0DH,0AH
DB '4. INCIDENT REPORTING AND PENALTY EXTENSION',0DH,0AH
DB '5. PAROLE ELIGIBILITY CHECKER',0DH,0AH
DB '6. INMATE TRANSFER BETWEEN CELL BLOCKS',0DH,0AH
DB '0. EXIT',0DH,0AH
DB 'ENTER CHOICE: $'

MSG_BAD_MENU DB 0DH,0AH,'INVALID MENU CHOICE. TRY AGAIN.$'
MSG_EXIT DB 0DH,0AH,'EXITING SYSTEM...$'
MSG_NO_DATA DB 0DH,0AH,'NO INMATE RECORD FOUND. USE FEATURE 1 FIRST.$'

; FEATURE 1 AND 2 MESSAGES

MSG_TITLE DB 13,10,'PRISON & INMATE RECORD MANAGEMENT SYSTEM$'
MSG_COUNT DB 13,10,'HOW MANY INMATES? MAX 10: $'
MSG_INVALID DB 13,10,'INVALID INPUT. ENTER AGAIN.$'

MSG_ID DB 13,10,'ENTER ID: $'
MSG_DUP DB 13,10,'DUPLICATE ID. ENTER ID AGAIN.$'

MSG_NAME DB 13,10,'ENTER NAME: $'
MSG_AGE DB 13,10,'ENTER AGE: $'
MSG_CRIME DB 13,10,'ENTER CRIME CATEGORY: $'

MSG_DUR_TITLE DB 13,10,'ENTER SENTENCE DURATION:$'
MSG_DUR_DAY DB 13,10,'ENTER DURATION DAYS 0-30: $'
MSG_DUR_MONTH DB 13,10,'ENTER DURATION MONTH 0-12: $'
MSG_DUR_YEAR DB 13,10,'ENTER DURATION YEAR: $'

MSG_DAY DB 13,10,'ENTER INTAKE DAY 1-30: $'
MSG_MONTH DB 13,10,'ENTER INTAKE MONTH 1-12: $'
MSG_YEAR DB 13,10,'ENTER INTAKE YEAR: $'

MSG_RELEASE DB 13,10,'RELEASE DATE: $'
MSG_SLASH DB '/$'
MSG_ALL_DONE DB 13,10,'ALL INMATE RECORDS SAVED.$'

MSG_RELEASING DB 13,10,'INMATES RELEASING THIS MONTH:$'
MSG_NO_FOUND DB 13,10,'NO INMATES FOUND.$'

MSG_MODIFY_ID DB 13,10,'ENTER INMATE ID TO MODIFY SENTENCE: $'
MSG_MODIFY_TYPE DB 13,10,'ENTER 1 TO EXTEND SENTENCE, 0 TO DECREASE SENTENCE: $'
MSG_MOD_DAY DB 13,10,'ENTER MODIFICATION DAYS 0-30: $'
MSG_MOD_MONTH DB 13,10,'ENTER MODIFICATION MONTHS 0-12: $'
MSG_MOD_YEAR DB 13,10,'ENTER MODIFICATION YEARS: $'
MSG_ID_NOT_FOUND DB 13,10,'INMATE ID NOT FOUND.$'
MSG_UPDATED DB 13,10,'UPDATED RELEASE DATE: $'

; FEATURE 3 MESSAGES

MSG_BLOCK_TITLE DB 0DH,0AH,'--- FEATURE 3: CELL BLOCK ASSIGNMENT ---$'
MSG_BLOCK_ID DB 0DH,0AH,'ENTER INMATE ID FOR BLOCK ASSIGNMENT: $'

MSG_SEVERITY DB 0DH,0AH,'SELECT CRIME SEVERITY:',0DH,0AH
DB '1. LOW    -> BLOCK A',0DH,0AH
DB '2. MEDIUM -> BLOCK B',0DH,0AH
DB '3. HIGH   -> BLOCK C',0DH,0AH
DB 'ENTER CHOICE: $'

MSG_BAD_SEVERITY DB 0DH,0AH,'ERROR: INVALID SEVERITY. TRY AGAIN.$'
MSG_ALREADY_ASSIGNED DB 0DH,0AH,'ERROR: INMATE ALREADY ASSIGNED TO A BLOCK.$'
MSG_BLOCK_FULL DB 0DH,0AH,'ERROR: SELECTED BLOCK IS FULL.$'
MSG_ASSIGN_OK DB 0DH,0AH,'BLOCK ASSIGNED SUCCESSFULLY.$'
MSG_ASSIGNED_BLOCK DB 0DH,0AH,'ASSIGNED BLOCK: $'
MSG_ASSIGN_AGAIN DB 0DH,0AH,'DO YOU WANT TO ASSIGN ANOTHER INMATE? Y/N: $'

MSG_BLOCK_A DB 'BLOCK A$'
MSG_BLOCK_B DB 'BLOCK B$'
MSG_BLOCK_C DB 'BLOCK C$'

MSG_OCC_TITLE DB 0DH,0AH,'CURRENT BLOCK OCCUPANCY:$'
MSG_OCC_A DB 0DH,0AH,'BLOCK A: $'
MSG_OCC_B DB 0DH,0AH,'BLOCK B: $'
MSG_OCC_C DB 0DH,0AH,'BLOCK C: $'
MSG_SLASH_CAP DB '/$'

; FEATURE 4 MESSAGES

MSG_INC_TITLE DB 0DH,0AH,'--- FEATURE 4: INCIDENT REPORTING ---$'

MSG_BAD_INPUT DB 0DH,0AH,'ERROR: INVALID ID INPUT. TRY AGAIN.$'
MSG_NOT_FOUND DB 0DH,0AH,'ERROR: INMATE ID NOT FOUND. TRY AGAIN.$'
MSG_FULL DB 0DH,0AH,'ERROR: INCIDENT STORAGE FULL.$'

MSG_TYPE DB 0DH,0AH,'SELECT INCIDENT TYPE:',0DH,0AH
DB '1. FIGHTING        (+15 DAYS)',0DH,0AH
DB '2. SMUGGLING       (+30 DAYS)',0DH,0AH
DB '3. ESCAPE ATTEMPT  (+60 DAYS)',0DH,0AH
DB '4. OTHER           (+10 DAYS)',0DH,0AH
DB 'ENTER CHOICE: $'

MSG_BAD_TYPE DB 0DH,0AH,'ERROR: INVALID INCIDENT TYPE. TRY AGAIN.$'
MSG_NOTE DB 0DH,0AH,'ENTER SHORT INCIDENT NOTE, MAX 30 CHARS: $'

MSG_OK DB 0DH,0AH,'INCIDENT RECORDED SUCCESSFULLY.$'
MSG_OUT_ID DB 0DH,0AH,'INMATE ID: $'
MSG_OUT_PENALTY DB 0DH,0AH,'PENALTY ADDED IN DAYS: $'
MSG_OUT_SENTENCE DB 0DH,0AH,'UPDATED SENTENCE DAYS: $'
MSG_OUT_RELEASE DB 0DH,0AH,'UPDATED RELEASE DATE: $'
MSG_OUT_COUNT DB 0DH,0AH,'TOTAL INCIDENTS FOR THIS INMATE: $'

MSG_AGAIN DB 0DH,0AH,0DH,0AH,'DO YOU WANT TO RECORD ANOTHER INCIDENT? Y/N: $'

; FEATURE 5 MESSAGES

MSG_PAROLE_TITLE DB 0DH,0AH,0DH,0AH,'--- FEATURE 5: PAROLE ELIGIBILITY CHECKER ---$'
MSG_DATE DB 0DH,0AH,'CURRENT SIMULATED DATE: $'
MSG_CUR_DAY DB 0DH,0AH,'ENTER CURRENT DAY 1-30: $'
MSG_CUR_MONTH DB 0DH,0AH,'ENTER CURRENT MONTH 1-12: $'
MSG_CUR_YEAR DB 0DH,0AH,'ENTER CURRENT YEAR: $'

MSG_ELIGIBLE DB 0DH,0AH,'ELIGIBLE INMATE ID: $'
MSG_SERVED DB ' | SERVED: $'
MSG_TOTAL_INC DB ' | TOTAL INCIDENTS: $'
MSG_NO_PAROLE DB 0DH,0AH,'NO INMATE IS ELIGIBLE FOR PAROLE NOW.$'
MSG_PAROLE_COUNT DB 0DH,0AH,'TOTAL PAROLE RECOMMENDATIONS: $'

MSG_PAROLE_ID DB 0DH,0AH,'ENTER INMATE ID FOR PAROLE CHECK: $'
MSG_PAROLE_STATUS DB 0DH,0AH,'PAROLE STATUS: $'
MSG_PAROLE_YES DB 'ELIGIBLE$'
MSG_PAROLE_NO DB 'NOT ELIGIBLE$'
MSG_REASON_RELEASED DB 0DH,0AH,'REASON: INMATE ALREADY REACHED RELEASE DATE.$'
MSG_REASON_INCIDENT DB 0DH,0AH,'REASON: RECENT INCIDENT FOUND.$'
MSG_REASON_TIME DB 0DH,0AH,'REASON: MINIMUM SERVED TIME NOT COMPLETED.$'
MSG_REASON_NOT_INTAKE DB 0DH,0AH,'REASON: CURRENT DATE IS BEFORE INTAKE DATE.$'
MSG_REQUIRED DB 0DH,0AH,'REQUIRED SERVED: $'
MSG_RECENT DB 0DH,0AH,'RECENT INCIDENT: $'
MSG_YES DB 'YES$'
MSG_NO DB 'NO$'
MSG_Y DB 'Y $'
MSG_M DB 'M $'
MSG_D DB 'D$'

; FEATURE 6 MESSAGES

MSG_TRANSFER_TITLE DB 0DH,0AH,'--- FEATURE 6: INMATE TRANSFER BETWEEN CELL BLOCKS ---$'
MSG_TRANSFER_ID DB 0DH,0AH,'ENTER INMATE ID FOR TRANSFER: $'

MSG_DEST_BLOCK DB 0DH,0AH,'SELECT DESTINATION BLOCK:',0DH,0AH
DB '1. BLOCK A',0DH,0AH
DB '2. BLOCK B',0DH,0AH
DB '3. BLOCK C',0DH,0AH
DB 'ENTER CHOICE: $'

MSG_BAD_BLOCK DB 0DH,0AH,'ERROR: INVALID BLOCK. TRY AGAIN.$'
MSG_NOT_ASSIGNED DB 0DH,0AH,'ERROR: INMATE IS NOT ASSIGNED TO ANY BLOCK.$'
MSG_SAME_BLOCK DB 0DH,0AH,'ERROR: DESTINATION BLOCK IS SAME AS CURRENT BLOCK.$'
MSG_TRANSFER_OK DB 0DH,0AH,'INMATE TRANSFERRED SUCCESSFULLY.$'
MSG_OLD_BLOCK DB 0DH,0AH,'OLD BLOCK: $'
MSG_NEW_BLOCK DB 0DH,0AH,'NEW BLOCK: $'
MSG_TRANSFER_AGAIN DB 0DH,0AH,'DO YOU WANT TO TRANSFER ANOTHER INMATE? Y/N: $'

.CODE

MAIN PROC

; initialize DS

MOV AX, @DATA
MOV DS, AX

; enter your code here

MAIN_MENU:

LEA DX, MSG_MAIN_MENU
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, '1'
JE MENU_FEATURE_1

CMP AL, '2'
JE MENU_FEATURE_2

CMP AL, '3'
JE MENU_FEATURE_3

CMP AL, '4'
JE MENU_FEATURE_4

CMP AL, '5'
JE MENU_FEATURE_5

CMP AL, '6'
JE MENU_FEATURE_6

CMP AL, '0'
JE EXIT_SYSTEM

LEA DX, MSG_BAD_MENU
CALL PRINT_STRING
JMP MAIN_MENU

MENU_FEATURE_1:
CALL INTAKE_PROFILE
JMP MAIN_MENU

MENU_FEATURE_2:
CMP COUNT, 0
JE NO_RECORD_FOR_FEATURE
CALL INPUT_CURRENT_DATE
CALL CHECK_RELEASE_MONTH
CALL MODIFY_SENTENCE
JMP MAIN_MENU

MENU_FEATURE_3:
CMP COUNT, 0
JE NO_RECORD_FOR_FEATURE
CALL CELL_BLOCK_ASSIGNMENT
JMP MAIN_MENU

MENU_FEATURE_4:
CMP COUNT, 0
JE NO_RECORD_FOR_FEATURE
CALL INCIDENT_REPORTING
JMP MAIN_MENU

MENU_FEATURE_5:
CMP COUNT, 0
JE NO_RECORD_FOR_FEATURE
CALL INPUT_CURRENT_DATE
CALL CHECK_ONE_PAROLE
CALL PAROLE_CHECKER
JMP MAIN_MENU

MENU_FEATURE_6:
CMP COUNT, 0
JE NO_RECORD_FOR_FEATURE
CALL TRANSFER_CELL_BLOCK
JMP MAIN_MENU

NO_RECORD_FOR_FEATURE:
LEA DX, MSG_NO_DATA
CALL PRINT_STRING
JMP MAIN_MENU

EXIT_SYSTEM:
LEA DX, MSG_EXIT
CALL PRINT_STRING

;exit to DOS

MOV AX, 4C00H
INT 21H

MAIN ENDP

; COMMON SUPPORT PROCEDURE
; PRINT_STRING

PRINT_STRING PROC NEAR

MOV AH, 9
INT 21H

RET

PRINT_STRING ENDP

; COMMON SUPPORT PROCEDURE
; READ_NUM

READ_NUM PROC NEAR

MOV BX, 0
MOV NUM_DIGITS, 0
MOV INPUT_ERR, 0

READ_NUM_LOOP:

MOV AH, 1
INT 21H

CMP AL, 0DH
JE READ_NUM_DONE

CMP AL, '0'
JL READ_NUM_BAD

CMP AL, '9'
JG READ_NUM_BAD

SUB AL, 30H
MOV AH, 0

PUSH AX

MOV AX, BX
MOV CX, 10
MUL CX

MOV BX, AX

POP AX
ADD BX, AX

INC NUM_DIGITS

JMP READ_NUM_LOOP

READ_NUM_BAD:

MOV INPUT_ERR, 1
JMP READ_NUM_LOOP

READ_NUM_DONE:

CMP NUM_DIGITS, 0
JNE READ_NUM_OK

MOV INPUT_ERR, 1

READ_NUM_OK:

MOV AX, BX

RET

READ_NUM ENDP

; COMMON SUPPORT PROCEDURE
; PRINT_NUM

PRINT_NUM PROC NEAR

PUSH AX
PUSH BX
PUSH CX
PUSH DX

CMP AX, 0
JNE PRINT_NUM_CONVERT

MOV DL, '0'
MOV AH, 2
INT 21H

JMP PRINT_NUM_DONE

PRINT_NUM_CONVERT:

MOV CX, 0
MOV BX, 10

PRINT_NUM_LOOP:

MOV DX, 0
DIV BX

ADD DL, 30H
PUSH DX

INC CX

CMP AX, 0
JNE PRINT_NUM_LOOP

PRINT_NUM_SHOW:

POP DX
MOV AH, 2
INT 21H

LOOP PRINT_NUM_SHOW

PRINT_NUM_DONE:

POP DX
POP CX
POP BX
POP AX

RET

PRINT_NUM ENDP

; COMMON SUPPORT PROCEDURE
; READ_STRING_PROC

READ_STRING_PROC PROC NEAR

MOV STR_LEN_TEMP, 0

READ_STRING_LOOP:

MOV AH, 1
INT 21H

CMP AL, 0DH
JE READ_STRING_DONE

MOV BL, STR_LEN_TEMP
CMP BL, MAX_TEMP
JGE READ_STRING_LOOP

MOV [DI], AL
INC DI

INC BL
MOV STR_LEN_TEMP, BL

JMP READ_STRING_LOOP

READ_STRING_DONE:

RET

READ_STRING_PROC ENDP

; FEATURE 1: INMATE INTAKE AND PROFILE CREATION

INTAKE_PROFILE PROC NEAR

LEA DX, MSG_TITLE
CALL PRINT_STRING

ASK_COUNT:

LEA DX, MSG_COUNT
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_COUNT

CMP AX, 10
JG INVALID_COUNT

CMP AX, 1
JL INVALID_COUNT

; check if old count + new count is more than 10
MOV BX, AX

MOV AL, COUNT
MOV AH, 0

ADD AX, BX

CMP AX, 10
JG INVALID_COUNT

; REMAINING = number of new inmates to add
MOV AX, BX
MOV REMAINING, AL

JMP COUNT_OK

INVALID_COUNT:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP ASK_COUNT

COUNT_OK:

INPUT_RECORD:

CMP REMAINING, 0
JE FINISH_ALL

; SI = COUNT * 2
; This starts saving after the last existing inmate
MOV AL, COUNT
MOV AH, 0
MOV BX, 2
MUL BX
MOV SI, AX

READ_ID_AGAIN:

LEA DX, MSG_ID
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE BAD_ID_FEATURE1

MOV TEMP_ID, AX

; check duplicate against all existing saved inmates
MOV AL, COUNT
CMP AL, 0
JE ID_NOT_DUPLICATE

MOV DI, 0
MOV CL, COUNT
MOV CH, 0

CHECK_DUPLICATE:

MOV AX, INMATE_IDS[DI]
CMP AX, TEMP_ID
JE DUPLICATE_FOUND

ADD DI, 2

LOOP CHECK_DUPLICATE

JMP ID_NOT_DUPLICATE

BAD_ID_FEATURE1:

LEA DX, MSG_BAD_INPUT
CALL PRINT_STRING
JMP READ_ID_AGAIN

DUPLICATE_FOUND:

LEA DX, MSG_DUP
CALL PRINT_STRING
JMP READ_ID_AGAIN

ID_NOT_DUPLICATE:

MOV AX, TEMP_ID
MOV INMATE_IDS[SI], AX

LEA DX, MSG_NAME
CALL PRINT_STRING

; name offset = COUNT * 20
MOV AL, COUNT
MOV AH, 0
MOV BX, 20
MUL BX
LEA DI, NAMES
ADD DI, AX

MOV MAX_TEMP, 20
CALL READ_STRING_PROC

MOV AL, COUNT
MOV AH, 0
MOV BX, AX
MOV AL, STR_LEN_TEMP
MOV NAMELEN[BX], AL

LEA DX, MSG_AGE
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE BAD_AGE

MOV AGE[SI], AX
JMP AGE_OK

BAD_AGE:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP INPUT_RECORD

AGE_OK:

LEA DX, MSG_CRIME
CALL PRINT_STRING

; crime offset = COUNT * 15
MOV AL, COUNT
MOV AH, 0
MOV BX, 15
MUL BX
LEA DI, CRIMES
ADD DI, AX

MOV MAX_TEMP, 15
CALL READ_STRING_PROC

MOV AL, COUNT
MOV AH, 0
MOV BX, AX
MOV AL, STR_LEN_TEMP
MOV CRIMELEN[BX], AL

LEA DX, MSG_DUR_TITLE
CALL PRINT_STRING

READ_DURATION_DAY:

LEA DX, MSG_DUR_DAY
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_DURATION_DAY

CMP AX, 30
JG INVALID_DURATION_DAY

CMP AX, 0
JL INVALID_DURATION_DAY

MOV DURATION_DAY[SI], AX
JMP READ_DURATION_MONTH

INVALID_DURATION_DAY:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_DURATION_DAY

READ_DURATION_MONTH:

LEA DX, MSG_DUR_MONTH
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_DURATION_MONTH

CMP AX, 12
JG INVALID_DURATION_MONTH

CMP AX, 0
JL INVALID_DURATION_MONTH

MOV DURATION_MONTH[SI], AX
JMP READ_DURATION_YEAR

INVALID_DURATION_MONTH:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_DURATION_MONTH

READ_DURATION_YEAR:

LEA DX, MSG_DUR_YEAR
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_DURATION_YEAR

MOV DURATION_YEAR[SI], AX
JMP READ_INTAKE_DAY

INVALID_DURATION_YEAR:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_DURATION_YEAR

READ_INTAKE_DAY:

LEA DX, MSG_DAY
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_INTAKE_DAY

CMP AX, 30
JG INVALID_INTAKE_DAY

CMP AX, 1
JL INVALID_INTAKE_DAY

MOV INTAKE_DAY[SI], AX
JMP READ_INTAKE_MONTH

INVALID_INTAKE_DAY:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_INTAKE_DAY

READ_INTAKE_MONTH:

LEA DX, MSG_MONTH
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_INTAKE_MONTH

CMP AX, 12
JG INVALID_INTAKE_MONTH

CMP AX, 1
JL INVALID_INTAKE_MONTH

MOV INTAKE_MONTH[SI], AX
JMP READ_INTAKE_YEAR

INVALID_INTAKE_MONTH:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_INTAKE_MONTH

READ_INTAKE_YEAR:

LEA DX, MSG_YEAR
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_INTAKE_YEAR

MOV INTAKE_YEAR[SI], AX

CALL CALC_RELEASE

LEA DX, MSG_RELEASE
CALL PRINT_STRING

MOV AX, RELEASE_DAY[SI]
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, RELEASE_MONTH[SI]
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, RELEASE_YEAR[SI]
CALL PRINT_NUM

; one inmate saved successfully
INC COUNT
DEC REMAINING

JMP INPUT_RECORD

INVALID_INTAKE_YEAR:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_INTAKE_YEAR

FINISH_ALL:

LEA DX, MSG_ALL_DONE
CALL PRINT_STRING

RET

INTAKE_PROFILE ENDP


; SUPPORT PROCEDURE FOR FEATURE 1, 2, AND 4

NORMALIZE_DURATION PROC NEAR

MOV AX, DURATION_DAY[SI]
MOV DX, 0
MOV BX, 30
DIV BX

CMP DX, 0
JE NORM_DAY_30

MOV DURATION_DAY[SI], DX
ADD DURATION_MONTH[SI], AX
JMP NORM_DAY_DONE

NORM_DAY_30:

CMP AX, 0
JE NORM_DAY_DONE

DEC AX
MOV DURATION_DAY[SI], 30
ADD DURATION_MONTH[SI], AX

NORM_DAY_DONE:

MOV AX, DURATION_MONTH[SI]
MOV DX, 0
MOV BX, 12
DIV BX

CMP DX, 0
JE NORM_MONTH_12

MOV DURATION_MONTH[SI], DX
ADD DURATION_YEAR[SI], AX
JMP NORM_DONE

NORM_MONTH_12:

CMP AX, 0
JE NORM_DONE

DEC AX
MOV DURATION_MONTH[SI], 12
ADD DURATION_YEAR[SI], AX

NORM_DONE:

RET

NORMALIZE_DURATION ENDP

; FEATURE 2 SUPPORT: RELEASE DATE CALCULATION

CALC_RELEASE PROC NEAR

CALL NORMALIZE_DURATION

MOV AX, INTAKE_DAY[SI]
ADD AX, DURATION_DAY[SI]

MOV DX, 0
MOV BX, 30
DIV BX

CMP DX, 0
JE REL_DAY_30

MOV EXTRA_MONTH, AX
MOV RELEASE_DAY[SI], DX
JMP REL_DAY_DONE

REL_DAY_30:

DEC AX
MOV EXTRA_MONTH, AX
MOV RELEASE_DAY[SI], 30

REL_DAY_DONE:

MOV AX, INTAKE_MONTH[SI]
ADD AX, DURATION_MONTH[SI]
ADD AX, EXTRA_MONTH

MOV DX, 0
MOV BX, 12
DIV BX

CMP DX, 0
JE REL_MONTH_12

MOV EXTRA_YEAR, AX
MOV RELEASE_MONTH[SI], DX
JMP REL_MONTH_DONE

REL_MONTH_12:

DEC AX
MOV EXTRA_YEAR, AX
MOV RELEASE_MONTH[SI], 12

REL_MONTH_DONE:

MOV AX, INTAKE_YEAR[SI]
ADD AX, DURATION_YEAR[SI]
ADD AX, EXTRA_YEAR
MOV RELEASE_YEAR[SI], AX

RET

CALC_RELEASE ENDP

; COMMON CURRENT DATE INPUT FOR FEATURE 2 AND FEATURE 5

INPUT_CURRENT_DATE PROC NEAR

READ_CURRENT_DAY:

LEA DX, MSG_CUR_DAY
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_CURRENT_DAY

CMP AX, 30
JG INVALID_CURRENT_DAY

CMP AX, 1
JL INVALID_CURRENT_DAY

MOV CURRENT_INPUT_DAY, AX
JMP READ_CURRENT_MONTH

INVALID_CURRENT_DAY:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_CURRENT_DAY

READ_CURRENT_MONTH:

LEA DX, MSG_CUR_MONTH
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_CURRENT_MONTH2

CMP AX, 12
JG INVALID_CURRENT_MONTH2

CMP AX, 1
JL INVALID_CURRENT_MONTH2

MOV CURRENT_INPUT_MONTH, AX
JMP READ_CURRENT_YEAR

INVALID_CURRENT_MONTH2:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_CURRENT_MONTH

READ_CURRENT_YEAR:

LEA DX, MSG_CUR_YEAR
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_CURRENT_YEAR

MOV CURRENT_INPUT_YEAR, AX

RET

INVALID_CURRENT_YEAR:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_CURRENT_YEAR

INPUT_CURRENT_DATE ENDP

; FEATURE 2: RELEASE MONTH CHECKER

CHECK_RELEASE_MONTH PROC NEAR

LEA DX, MSG_RELEASING
CALL PRINT_STRING

MOV FOUND, 0
MOV SI, 0
MOV INMATE_NO, 0
MOV AL, COUNT
MOV REMAINING, AL

CHECK_MONTH_LOOP:

CMP REMAINING, 0
JE END_CHECK_MONTH

MOV AX, RELEASE_MONTH[SI]
CMP AX, CURRENT_INPUT_MONTH
JNE NEXT_INMATE_MONTH

MOV AX, RELEASE_YEAR[SI]
CMP AX, CURRENT_INPUT_YEAR
JNE NEXT_INMATE_MONTH

MOV FOUND, 1

MOV DL, 13
MOV AH, 2
INT 21H

MOV DL, 10
MOV AH, 2
INT 21H

MOV AL, INMATE_NO
MOV AH, 0
MOV BX, 20
MUL BX

LEA DI, NAMES
ADD DI, AX

MOV AL, INMATE_NO
MOV AH, 0
MOV BX, AX

MOV CL, NAMELEN[BX]
MOV CH, 0

PRINT_NAME_LOOP:

CMP CX, 0
JE NAME_PRINT_DONE

MOV DL, [DI]
MOV AH, 2
INT 21H

INC DI
DEC CX

JMP PRINT_NAME_LOOP

NAME_PRINT_DONE:

NEXT_INMATE_MONTH:

ADD SI, 2
INC INMATE_NO
DEC REMAINING

JMP CHECK_MONTH_LOOP

END_CHECK_MONTH:

CMP FOUND, 0
JNE EXIT_RELEASE_CHECK

LEA DX, MSG_NO_FOUND
CALL PRINT_STRING

EXIT_RELEASE_CHECK:

RET

CHECK_RELEASE_MONTH ENDP

; FEATURE 2: Sentence modification

MODIFY_SENTENCE PROC NEAR

START_MODIFY_ID:

LEA DX, MSG_MODIFY_ID
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE MODIFY_BAD_INPUT

MOV SEARCH_ID, AX

CALL FIND_INMATE

CMP FOUND_FLAG, 1
JNE MODIFY_ID_NOT_FOUND

MOV BX, FOUND_INDEX
ADD BX, BX
MOV SI, BX

ASK_MODIFY_TYPE:

LEA DX, MSG_MODIFY_TYPE
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE BAD_MODIFY_TYPE

CMP AX, 1
JE EXTEND_SENTENCE

CMP AX, 0
JE DECREASE_SENTENCE

BAD_MODIFY_TYPE:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP ASK_MODIFY_TYPE

EXTEND_SENTENCE:

CALL READ_MODIFICATION_VALUES

MOV AX, DURATION_DAY[SI]
ADD AX, MOD_DAY
MOV DURATION_DAY[SI], AX

MOV AX, DURATION_MONTH[SI]
ADD AX, MOD_MONTH
MOV DURATION_MONTH[SI], AX

MOV AX, DURATION_YEAR[SI]
ADD AX, MOD_YEAR
MOV DURATION_YEAR[SI], AX

CALL CALC_RELEASE
CALL DISPLAY_UPDATED_RELEASE

RET

DECREASE_SENTENCE:

CALL READ_MODIFICATION_VALUES

MOV AX, DURATION_DAY[SI]
CMP AX, MOD_DAY
JL SET_DAY_ZERO

SUB AX, MOD_DAY
MOV DURATION_DAY[SI], AX
JMP DECREASE_MONTH_PART

SET_DAY_ZERO:

MOV DURATION_DAY[SI], 0

DECREASE_MONTH_PART:

MOV AX, DURATION_MONTH[SI]
CMP AX, MOD_MONTH
JL SET_MONTH_ZERO

SUB AX, MOD_MONTH
MOV DURATION_MONTH[SI], AX
JMP DECREASE_YEAR_PART

SET_MONTH_ZERO:

MOV DURATION_MONTH[SI], 0

DECREASE_YEAR_PART:

MOV AX, DURATION_YEAR[SI]
CMP AX, MOD_YEAR
JL SET_YEAR_ZERO

SUB AX, MOD_YEAR
MOV DURATION_YEAR[SI], AX
JMP AFTER_DECREASE

SET_YEAR_ZERO:

MOV DURATION_YEAR[SI], 0

AFTER_DECREASE:

CALL CALC_RELEASE
CALL DISPLAY_UPDATED_RELEASE

RET

MODIFY_BAD_INPUT:

LEA DX, MSG_BAD_INPUT
CALL PRINT_STRING
JMP START_MODIFY_ID

MODIFY_ID_NOT_FOUND:

LEA DX, MSG_ID_NOT_FOUND
CALL PRINT_STRING
JMP START_MODIFY_ID

MODIFY_SENTENCE ENDP

READ_MODIFICATION_VALUES PROC NEAR

READ_MOD_DAY:

LEA DX, MSG_MOD_DAY
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_MOD_DAY

CMP AX, 30
JG INVALID_MOD_DAY

CMP AX, 0
JL INVALID_MOD_DAY

MOV MOD_DAY, AX
JMP READ_MOD_MONTH

INVALID_MOD_DAY:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_MOD_DAY

READ_MOD_MONTH:

LEA DX, MSG_MOD_MONTH
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_MOD_MONTH

CMP AX, 12
JG INVALID_MOD_MONTH

CMP AX, 0
JL INVALID_MOD_MONTH

MOV MOD_MONTH, AX
JMP READ_MOD_YEAR

INVALID_MOD_MONTH:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_MOD_MONTH

READ_MOD_YEAR:

LEA DX, MSG_MOD_YEAR
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE INVALID_MOD_YEAR

MOV MOD_YEAR, AX

RET

INVALID_MOD_YEAR:

LEA DX, MSG_INVALID
CALL PRINT_STRING
JMP READ_MOD_YEAR

READ_MODIFICATION_VALUES ENDP

DISPLAY_UPDATED_RELEASE PROC NEAR

LEA DX, MSG_UPDATED
CALL PRINT_STRING

MOV AX, RELEASE_DAY[SI]
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, RELEASE_MONTH[SI]
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, RELEASE_YEAR[SI]
CALL PRINT_NUM

RET

DISPLAY_UPDATED_RELEASE ENDP

FIND_INMATE PROC NEAR

MOV FOUND_FLAG, 0

MOV AL, COUNT
CMP AL, 0
JE FIND_END

LEA SI, INMATE_IDS
MOV CL, COUNT
MOV CH, 0
MOV DI, 0

FIND_LOOP:

MOV AX, [SI]
CMP AX, SEARCH_ID
JE FIND_SUCCESS

ADD SI, 2
INC DI

LOOP FIND_LOOP

JMP FIND_END

FIND_SUCCESS:

MOV FOUND_FLAG, 1
MOV FOUND_INDEX, DI

FIND_END:

RET

FIND_INMATE ENDP

; FEATURE 3: CELL BLOCK ASSIGNMENT AND OCCUPANCY MANAGEMENT

CELL_BLOCK_ASSIGNMENT PROC NEAR

LEA DX, MSG_BLOCK_TITLE
CALL PRINT_STRING

ASSIGN_START:

LEA DX, MSG_BLOCK_ID
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE ASSIGN_BAD_ID

MOV SEARCH_ID, AX

CALL FIND_INMATE

CMP FOUND_FLAG, 1
JNE ASSIGN_ID_NOT_FOUND

MOV BX, FOUND_INDEX
MOV AL, INMATE_BLOCK[BX]
CMP AL, 0
JNE ASSIGN_ALREADY_DONE

ASK_SEVERITY:

LEA DX, MSG_SEVERITY
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, '1'
JE SEVERITY_LOW

CMP AL, '2'
JE SEVERITY_MEDIUM

CMP AL, '3'
JE SEVERITY_HIGH

JMP BAD_SEVERITY

SEVERITY_LOW:

MOV BLOCK_TEMP, 1
JMP CHECK_ASSIGN_CAPACITY

SEVERITY_MEDIUM:

MOV BLOCK_TEMP, 2
JMP CHECK_ASSIGN_CAPACITY

SEVERITY_HIGH:

MOV BLOCK_TEMP, 3
JMP CHECK_ASSIGN_CAPACITY

CHECK_ASSIGN_CAPACITY:

MOV AL, BLOCK_TEMP
DEC AL
MOV AH, 0
MOV SI, AX

MOV AL, BLOCK_OCCUPANCY[SI]
CMP AL, BLOCK_CAPACITY[SI]
JE ASSIGN_BLOCK_FULL

MOV BX, FOUND_INDEX
MOV AL, BLOCK_TEMP
MOV INMATE_BLOCK[BX], AL

MOV AL, BLOCK_OCCUPANCY[SI]
INC AL
MOV BLOCK_OCCUPANCY[SI], AL

LEA DX, MSG_ASSIGN_OK
CALL PRINT_STRING

LEA DX, MSG_OUT_ID
CALL PRINT_STRING

MOV AX, SEARCH_ID
CALL PRINT_NUM

LEA DX, MSG_ASSIGNED_BLOCK
CALL PRINT_STRING

MOV AL, BLOCK_TEMP
CALL PRINT_BLOCK_NAME

CALL DISPLAY_BLOCK_OCCUPANCY

ASK_ASSIGN_AGAIN:

LEA DX, MSG_ASSIGN_AGAIN
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, 'Y'
JE ASSIGN_START

CMP AL, 'y'
JE ASSIGN_START

CMP AL, 'N'
JE ASSIGN_DONE

CMP AL, 'n'
JE ASSIGN_DONE

JMP ASK_ASSIGN_AGAIN

ASSIGN_DONE:

RET

ASSIGN_BAD_ID:

LEA DX, MSG_BAD_INPUT
CALL PRINT_STRING
JMP ASSIGN_START

ASSIGN_ID_NOT_FOUND:

LEA DX, MSG_NOT_FOUND
CALL PRINT_STRING
JMP ASSIGN_START

ASSIGN_ALREADY_DONE:

LEA DX, MSG_ALREADY_ASSIGNED
CALL PRINT_STRING
JMP ASK_ASSIGN_AGAIN

BAD_SEVERITY:

LEA DX, MSG_BAD_SEVERITY
CALL PRINT_STRING
JMP ASK_SEVERITY

ASSIGN_BLOCK_FULL:

LEA DX, MSG_BLOCK_FULL
CALL PRINT_STRING
CALL DISPLAY_BLOCK_OCCUPANCY
JMP ASK_ASSIGN_AGAIN

CELL_BLOCK_ASSIGNMENT ENDP

; Feature 4: Incident reporting and penalty extension

INCIDENT_REPORTING PROC NEAR

LEA DX, MSG_INC_TITLE
CALL PRINT_STRING

ASK_ID_INCIDENT:

LEA DX, MSG_ID
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE BAD_ID_INPUT_INCIDENT

MOV SEARCH_ID, AX

CALL FIND_INMATE

CMP FOUND_FLAG, 1
JNE ID_NOT_FOUND_INCIDENT

MOV AL, INCIDENT_TOTAL
CMP AL, MAX_INCIDENTS
JL INCIDENT_SPACE_AVAILABLE

JMP INCIDENT_STORAGE_FULL

INCIDENT_SPACE_AVAILABLE:

ASK_TYPE:

LEA DX, MSG_TYPE
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, '1'
JL BAD_TYPE

CMP AL, '4'
JG BAD_TYPE

MOV CHOSEN_TYPE, AL

SUB AL, '1'
MOV AH, 0
MOV BX, AX
ADD BX, BX

MOV AX, PENALTY_DAYS[BX]
MOV PENALTY_TEMP, AX

MOV AL, INCIDENT_TOTAL
MOV AH, 0
MOV BL, 31
MUL BL

LEA DI, INCIDENT_NOTES
ADD DI, AX

LEA DX, MSG_NOTE
CALL PRINT_STRING

CALL READ_NOTE

MOV AL, INCIDENT_TOTAL
MOV AH, 0
MOV SI, AX

MOV AX, FOUND_INDEX
MOV INCIDENT_INMATE_INDEX[SI], AL

MOV AL, CHOSEN_TYPE
MOV INCIDENT_TYPE[SI], AL

MOV BX, SI
ADD BX, BX

MOV AX, PENALTY_TEMP
MOV INCIDENT_PENALTY[BX], AX

INC INCIDENT_TOTAL

MOV BX, FOUND_INDEX

MOV AL, TOTAL_INCIDENTS[BX]
INC AL
MOV TOTAL_INCIDENTS[BX], AL

MOV AL, 1
MOV RECENT_INCIDENT[BX], AL

MOV BX, FOUND_INDEX
ADD BX, BX
MOV SI, BX

MOV AX, DURATION_DAY[SI]
ADD AX, PENALTY_TEMP
MOV DURATION_DAY[SI], AX

CALL CALC_RELEASE

CALL DISPLAY_UPDATED_RECORD

ASK_AGAIN_INCIDENT:

LEA DX, MSG_AGAIN
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, 'Y'
JE ASK_ID_INCIDENT

CMP AL, 'y'
JE ASK_ID_INCIDENT

CMP AL, 'N'
JE INCIDENT_DONE

CMP AL, 'n'
JE INCIDENT_DONE

JMP ASK_AGAIN_INCIDENT

INCIDENT_DONE:

RET

BAD_ID_INPUT_INCIDENT:

LEA DX, MSG_BAD_INPUT
CALL PRINT_STRING
JMP ASK_ID_INCIDENT

ID_NOT_FOUND_INCIDENT:

LEA DX, MSG_NOT_FOUND
CALL PRINT_STRING
JMP ASK_ID_INCIDENT

BAD_TYPE:

LEA DX, MSG_BAD_TYPE
CALL PRINT_STRING
JMP ASK_TYPE

INCIDENT_STORAGE_FULL:

LEA DX, MSG_FULL
CALL PRINT_STRING
RET

INCIDENT_REPORTING ENDP

; Support procedure for feature 4

READ_NOTE PROC NEAR

MOV CX, 0

READ_NOTE_LOOP:

MOV AH, 1
INT 21H

CMP AL, 0DH
JE READ_NOTE_DONE

CMP CX, 30
JGE READ_NOTE_LOOP

MOV [DI], AL
INC DI
INC CX

JMP READ_NOTE_LOOP

READ_NOTE_DONE:

MOV AL, '$'
MOV [DI], AL

RET

READ_NOTE ENDP

; ===============================================================
; SUPPORT PROCEDURE FOR FEATURE 4
; DISPLAY_UPDATED_RECORD


DISPLAY_UPDATED_RECORD PROC NEAR

LEA DX, MSG_OK
CALL PRINT_STRING

LEA DX, MSG_OUT_ID
CALL PRINT_STRING

MOV AX, SEARCH_ID
CALL PRINT_NUM

LEA DX, MSG_OUT_PENALTY
CALL PRINT_STRING

MOV AX, PENALTY_TEMP
CALL PRINT_NUM

LEA DX, MSG_OUT_RELEASE
CALL PRINT_STRING

MOV AX, RELEASE_DAY[SI]
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, RELEASE_MONTH[SI]
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, RELEASE_YEAR[SI]
CALL PRINT_NUM

LEA DX, MSG_OUT_COUNT
CALL PRINT_STRING

MOV BX, FOUND_INDEX
MOV AL, TOTAL_INCIDENTS[BX]
MOV AH, 0
CALL PRINT_NUM

RET

DISPLAY_UPDATED_RECORD ENDP

; FEATURE 5 SUPPORT: CHECK CURRENT DATE BEFORE INTAKE

CHECK_BEFORE_INTAKE PROC NEAR

MOV DATE_FLAG, 0

MOV AX, CURRENT_INPUT_YEAR
CMP AX, INTAKE_YEAR[SI]
JL CURRENT_IS_BEFORE_INTAKE
JG CURRENT_NOT_BEFORE_INTAKE

MOV AX, CURRENT_INPUT_MONTH
CMP AX, INTAKE_MONTH[SI]
JL CURRENT_IS_BEFORE_INTAKE
JG CURRENT_NOT_BEFORE_INTAKE

MOV AX, CURRENT_INPUT_DAY
CMP AX, INTAKE_DAY[SI]
JL CURRENT_IS_BEFORE_INTAKE

CURRENT_NOT_BEFORE_INTAKE:

RET

CURRENT_IS_BEFORE_INTAKE:

MOV DATE_FLAG, 1
RET

CHECK_BEFORE_INTAKE ENDP

; FEATURE 5 SUPPORT: CHECK RELEASE DATE REACHED

CHECK_RELEASE_REACHED PROC NEAR

MOV DATE_FLAG, 0

MOV AX, CURRENT_INPUT_YEAR
CMP AX, RELEASE_YEAR[SI]
JG RELEASE_ALREADY_REACHED
JL RELEASE_NOT_REACHED

MOV AX, CURRENT_INPUT_MONTH
CMP AX, RELEASE_MONTH[SI]
JG RELEASE_ALREADY_REACHED
JL RELEASE_NOT_REACHED

MOV AX, CURRENT_INPUT_DAY
CMP AX, RELEASE_DAY[SI]
JL RELEASE_NOT_REACHED

RELEASE_ALREADY_REACHED:

MOV DATE_FLAG, 1
RET

RELEASE_NOT_REACHED:

RET

CHECK_RELEASE_REACHED ENDP

; FEATURE 5 SUPPORT: CALCULATE SERVED DURATION

CALC_SERVED_DURATION PROC NEAR

MOV AX, CURRENT_INPUT_DAY
MOV TEMP_DAY, AX

MOV AX, CURRENT_INPUT_MONTH
MOV TEMP_MONTH, AX

MOV AX, CURRENT_INPUT_YEAR
MOV TEMP_YEAR, AX


; Calculate served days

MOV AX, TEMP_DAY
CMP AX, INTAKE_DAY[SI]
JL BORROW_MONTH_FOR_DAY

SUB AX, INTAKE_DAY[SI]
MOV SERVED_DAY, AX
JMP SERVED_MONTH_PART


BORROW_MONTH_FOR_DAY:

ADD AX, 30
SUB AX, INTAKE_DAY[SI]
MOV SERVED_DAY, AX

MOV AX, TEMP_MONTH
DEC AX
MOV TEMP_MONTH, AX


; Calculate served months

SERVED_MONTH_PART:

MOV AX, TEMP_MONTH
CMP AX, INTAKE_MONTH[SI]
JL BORROW_YEAR_FOR_MONTH

SUB AX, INTAKE_MONTH[SI]
MOV SERVED_MONTH, AX
JMP SERVED_YEAR_PART


BORROW_YEAR_FOR_MONTH:

ADD AX, 12
SUB AX, INTAKE_MONTH[SI]
MOV SERVED_MONTH, AX

MOV AX, TEMP_YEAR
DEC AX
MOV TEMP_YEAR, AX


; Calculate served years

SERVED_YEAR_PART:

MOV AX, TEMP_YEAR
SUB AX, INTAKE_YEAR[SI]
MOV SERVED_YEAR, AX

RET

CALC_SERVED_DURATION ENDP

; FEATURE 5 SUPPORT: CALCULATE REQUIRED SERVED DURATION

CALC_REQUIRED_DURATION PROC NEAR

MOV AX, DURATION_YEAR[SI]
MOV REQUIRED_YEAR, AX

MOV AX, DURATION_MONTH[SI]
MOV REQUIRED_MONTH, AX

MOV AX, DURATION_DAY[SI]
MOV REQUIRED_DAY, AX

MOV AX, REQUIRED_YEAR
MOV DX, 0
MOV BX, 2
DIV BX
MOV REQUIRED_YEAR, AX

CMP DX, 0
JE REQ_MONTH_HALF

MOV AX, REQUIRED_MONTH
ADD AX, 12
MOV REQUIRED_MONTH, AX

REQ_MONTH_HALF:

MOV AX, REQUIRED_MONTH
MOV DX, 0
MOV BX, 2
DIV BX
MOV REQUIRED_MONTH, AX

CMP DX, 0
JE REQ_DAY_HALF

MOV AX, REQUIRED_DAY
ADD AX, 30
MOV REQUIRED_DAY, AX

REQ_DAY_HALF:

MOV AX, REQUIRED_DAY
MOV DX, 0
MOV BX, 2
DIV BX
MOV REQUIRED_DAY, AX

RET

CALC_REQUIRED_DURATION ENDP

; FEATURE 5 SUPPORT: CHECK MINIMUM SERVED TIME

CHECK_SERVED_ENOUGH PROC NEAR

MOV DATE_FLAG, 0

MOV AX, SERVED_YEAR
CMP AX, REQUIRED_YEAR
JG SERVED_ENOUGH
JL SERVED_NOT_ENOUGH

MOV AX, SERVED_MONTH
CMP AX, REQUIRED_MONTH
JG SERVED_ENOUGH
JL SERVED_NOT_ENOUGH

MOV AX, SERVED_DAY
CMP AX, REQUIRED_DAY
JL SERVED_NOT_ENOUGH

SERVED_ENOUGH:

MOV DATE_FLAG, 1
RET

SERVED_NOT_ENOUGH:

RET

CHECK_SERVED_ENOUGH ENDP

PRINT_DURATION PROC NEAR

MOV AX, SERVED_YEAR
CALL PRINT_NUM
LEA DX, MSG_Y
CALL PRINT_STRING

MOV AX, SERVED_MONTH
CALL PRINT_NUM
LEA DX, MSG_M
CALL PRINT_STRING

MOV AX, SERVED_DAY
CALL PRINT_NUM
LEA DX, MSG_D
CALL PRINT_STRING

RET

PRINT_DURATION ENDP

PRINT_REQUIRED PROC NEAR

MOV AX, REQUIRED_YEAR
CALL PRINT_NUM
LEA DX, MSG_Y
CALL PRINT_STRING

MOV AX, REQUIRED_MONTH
CALL PRINT_NUM
LEA DX, MSG_M
CALL PRINT_STRING

MOV AX, REQUIRED_DAY
CALL PRINT_NUM
LEA DX, MSG_D
CALL PRINT_STRING

RET

PRINT_REQUIRED ENDP

; FEATURE 5: ONE INMATE PAROLE ELIGIBILITY CHECKER

CHECK_ONE_PAROLE PROC NEAR

LEA DX, MSG_PAROLE_TITLE
CALL PRINT_STRING

LEA DX, MSG_PAROLE_ID
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE PAROLE_BAD_ID_INPUT

MOV SEARCH_ID, AX

CALL FIND_INMATE

CMP FOUND_FLAG, 1
JNE PAROLE_ID_NOT_FOUND

LEA DX, MSG_OUT_ID
CALL PRINT_STRING

MOV AX, SEARCH_ID
CALL PRINT_NUM

MOV BX, FOUND_INDEX
ADD BX, BX
MOV SI, BX

CALL CHECK_BEFORE_INTAKE

CMP DATE_FLAG, 1
JE PAROLE_BEFORE_INTAKE

CALL CHECK_RELEASE_REACHED

CMP DATE_FLAG, 1
JE PAROLE_ALREADY_RELEASED

CALL CALC_SERVED_DURATION

LEA DX, MSG_SERVED
CALL PRINT_STRING
CALL PRINT_DURATION

CALL CALC_REQUIRED_DURATION

LEA DX, MSG_REQUIRED
CALL PRINT_STRING
CALL PRINT_REQUIRED

MOV BX, FOUND_INDEX

LEA DX, MSG_RECENT
CALL PRINT_STRING

MOV AL, RECENT_INCIDENT[BX]
CMP AL, 0
JE PAROLE_NO_RECENT_INCIDENT

LEA DX, MSG_YES
CALL PRINT_STRING
JMP PAROLE_HAS_INCIDENT

PAROLE_NO_RECENT_INCIDENT:

LEA DX, MSG_NO
CALL PRINT_STRING

CALL CHECK_SERVED_ENOUGH

CMP DATE_FLAG, 1
JNE PAROLE_TIME_NOT_DONE

LEA DX, MSG_PAROLE_STATUS
CALL PRINT_STRING

LEA DX, MSG_PAROLE_YES
CALL PRINT_STRING

RET

PAROLE_HAS_INCIDENT:

LEA DX, MSG_PAROLE_STATUS
CALL PRINT_STRING

LEA DX, MSG_PAROLE_NO
CALL PRINT_STRING

LEA DX, MSG_REASON_INCIDENT
CALL PRINT_STRING

RET

PAROLE_TIME_NOT_DONE:

LEA DX, MSG_PAROLE_STATUS
CALL PRINT_STRING

LEA DX, MSG_PAROLE_NO
CALL PRINT_STRING

LEA DX, MSG_REASON_TIME
CALL PRINT_STRING

RET

PAROLE_ALREADY_RELEASED:

LEA DX, MSG_PAROLE_STATUS
CALL PRINT_STRING

LEA DX, MSG_PAROLE_NO
CALL PRINT_STRING

LEA DX, MSG_REASON_RELEASED
CALL PRINT_STRING

RET

PAROLE_BEFORE_INTAKE:

LEA DX, MSG_PAROLE_STATUS
CALL PRINT_STRING

LEA DX, MSG_PAROLE_NO
CALL PRINT_STRING

LEA DX, MSG_REASON_NOT_INTAKE
CALL PRINT_STRING

RET

PAROLE_BAD_ID_INPUT:

LEA DX, MSG_BAD_INPUT
CALL PRINT_STRING

RET

PAROLE_ID_NOT_FOUND:

LEA DX, MSG_NOT_FOUND
CALL PRINT_STRING

RET

CHECK_ONE_PAROLE ENDP

; FEATURE 5: PAROLE RECOMMENDATION LIST

PAROLE_CHECKER PROC NEAR

MOV ELIGIBLE_COUNT, 0

LEA DX, MSG_PAROLE_TITLE
CALL PRINT_STRING

LEA DX, MSG_DATE
CALL PRINT_STRING

MOV AX, CURRENT_INPUT_DAY
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, CURRENT_INPUT_MONTH
CALL PRINT_NUM

LEA DX, MSG_SLASH
CALL PRINT_STRING

MOV AX, CURRENT_INPUT_YEAR
CALL PRINT_NUM

MOV SI, 0
MOV DI, 0

MOV CL, COUNT
MOV CH, 0

PAROLE_LOOP:

CALL CHECK_BEFORE_INTAKE

CMP DATE_FLAG, 1
JE NOT_ELIGIBLE

CALL CHECK_RELEASE_REACHED

CMP DATE_FLAG, 1
JE NOT_ELIGIBLE

MOV AL, RECENT_INCIDENT[DI]
CMP AL, 0
JNE NOT_ELIGIBLE

CALL CALC_SERVED_DURATION
CALL CALC_REQUIRED_DURATION
CALL CHECK_SERVED_ENOUGH

CMP DATE_FLAG, 1
JNE NOT_ELIGIBLE

INC ELIGIBLE_COUNT

LEA DX, MSG_ELIGIBLE
CALL PRINT_STRING

MOV AX, INMATE_IDS[SI]
CALL PRINT_NUM

LEA DX, MSG_SERVED
CALL PRINT_STRING
CALL PRINT_DURATION

LEA DX, MSG_TOTAL_INC
CALL PRINT_STRING

MOV AL, TOTAL_INCIDENTS[DI]
MOV AH, 0
CALL PRINT_NUM

NOT_ELIGIBLE:

ADD SI, 2
INC DI

LOOP PAROLE_LOOP

CMP ELIGIBLE_COUNT, 0
JE NO_PAROLE_FOUND

LEA DX, MSG_PAROLE_COUNT
CALL PRINT_STRING

MOV AL, ELIGIBLE_COUNT
MOV AH, 0
CALL PRINT_NUM

JMP PAROLE_DONE

NO_PAROLE_FOUND:

LEA DX, MSG_NO_PAROLE
CALL PRINT_STRING

PAROLE_DONE:

RET

PAROLE_CHECKER ENDP

; FEATURE 6: INMATE TRANSFER BETWEEN CELL BLOCKS

TRANSFER_CELL_BLOCK PROC NEAR

LEA DX, MSG_TRANSFER_TITLE
CALL PRINT_STRING

TRANSFER_START:

LEA DX, MSG_TRANSFER_ID
CALL PRINT_STRING

CALL READ_NUM

CMP INPUT_ERR, 1
JE TRANSFER_BAD_ID

MOV SEARCH_ID, AX

CALL FIND_INMATE

CMP FOUND_FLAG, 1
JNE TRANSFER_ID_NOT_FOUND

MOV BX, FOUND_INDEX
MOV AL, INMATE_BLOCK[BX]
CMP AL, 0
JE TRANSFER_NOT_ASSIGNED

MOV OLD_BLOCK_TEMP, AL

ASK_DEST_BLOCK:

LEA DX, MSG_DEST_BLOCK
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, '1'
JE DEST_BLOCK_A

CMP AL, '2'
JE DEST_BLOCK_B

CMP AL, '3'
JE DEST_BLOCK_C

JMP BAD_DEST_BLOCK

DEST_BLOCK_A:

MOV DEST_BLOCK_TEMP, 1
JMP CHECK_TRANSFER_BLOCK

DEST_BLOCK_B:

MOV DEST_BLOCK_TEMP, 2
JMP CHECK_TRANSFER_BLOCK

DEST_BLOCK_C:

MOV DEST_BLOCK_TEMP, 3
JMP CHECK_TRANSFER_BLOCK

CHECK_TRANSFER_BLOCK:

MOV AL, DEST_BLOCK_TEMP
CMP AL, OLD_BLOCK_TEMP
JE TRANSFER_SAME_BLOCK

MOV AL, DEST_BLOCK_TEMP
DEC AL
MOV AH, 0
MOV SI, AX

MOV AL, BLOCK_OCCUPANCY[SI]
CMP AL, BLOCK_CAPACITY[SI]
JE TRANSFER_BLOCK_FULL

MOV AL, OLD_BLOCK_TEMP
DEC AL
MOV AH, 0
MOV DI, AX

MOV AL, BLOCK_OCCUPANCY[DI]
DEC AL
MOV BLOCK_OCCUPANCY[DI], AL

MOV AL, BLOCK_OCCUPANCY[SI]
INC AL
MOV BLOCK_OCCUPANCY[SI], AL

MOV BX, FOUND_INDEX
MOV AL, DEST_BLOCK_TEMP
MOV INMATE_BLOCK[BX], AL

LEA DX, MSG_TRANSFER_OK
CALL PRINT_STRING

LEA DX, MSG_OUT_ID
CALL PRINT_STRING

MOV AX, SEARCH_ID
CALL PRINT_NUM

LEA DX, MSG_OLD_BLOCK
CALL PRINT_STRING

MOV AL, OLD_BLOCK_TEMP
CALL PRINT_BLOCK_NAME

LEA DX, MSG_NEW_BLOCK
CALL PRINT_STRING

MOV AL, DEST_BLOCK_TEMP
CALL PRINT_BLOCK_NAME

CALL DISPLAY_BLOCK_OCCUPANCY

ASK_TRANSFER_AGAIN:

LEA DX, MSG_TRANSFER_AGAIN
CALL PRINT_STRING

MOV AH, 1
INT 21H

CMP AL, 'Y'
JE TRANSFER_START

CMP AL, 'y'
JE TRANSFER_START

CMP AL, 'N'
JE TRANSFER_DONE

CMP AL, 'n'
JE TRANSFER_DONE

JMP ASK_TRANSFER_AGAIN

TRANSFER_DONE:

RET

TRANSFER_BAD_ID:

LEA DX, MSG_BAD_INPUT
CALL PRINT_STRING
JMP TRANSFER_START

TRANSFER_ID_NOT_FOUND:

LEA DX, MSG_NOT_FOUND
CALL PRINT_STRING
JMP TRANSFER_START

TRANSFER_NOT_ASSIGNED:

LEA DX, MSG_NOT_ASSIGNED
CALL PRINT_STRING
JMP ASK_TRANSFER_AGAIN

BAD_DEST_BLOCK:

LEA DX, MSG_BAD_BLOCK
CALL PRINT_STRING
JMP ASK_DEST_BLOCK

TRANSFER_SAME_BLOCK:

LEA DX, MSG_SAME_BLOCK
CALL PRINT_STRING
JMP ASK_DEST_BLOCK

TRANSFER_BLOCK_FULL:

LEA DX, MSG_BLOCK_FULL
CALL PRINT_STRING
CALL DISPLAY_BLOCK_OCCUPANCY
JMP ASK_TRANSFER_AGAIN

TRANSFER_CELL_BLOCK ENDP

; SUPPORT PROCEDURE FOR FEATURE 3 AND FEATURE 6
; PRINT_BLOCK_NAME

PRINT_BLOCK_NAME PROC NEAR

CMP AL, 1
JE PRINT_BLOCK_A

CMP AL, 2
JE PRINT_BLOCK_B

CMP AL, 3
JE PRINT_BLOCK_C

RET

PRINT_BLOCK_A:

LEA DX, MSG_BLOCK_A
CALL PRINT_STRING
RET

PRINT_BLOCK_B:

LEA DX, MSG_BLOCK_B
CALL PRINT_STRING
RET

PRINT_BLOCK_C:

LEA DX, MSG_BLOCK_C
CALL PRINT_STRING
RET

PRINT_BLOCK_NAME ENDP

; SUPPORT PROCEDURE FOR FEATURE 3 AND FEATURE 6
; DISPLAY_BLOCK_OCCUPANCY

DISPLAY_BLOCK_OCCUPANCY PROC NEAR

LEA DX, MSG_OCC_TITLE
CALL PRINT_STRING

LEA DX, MSG_OCC_A
CALL PRINT_STRING

MOV AL, BLOCK_OCCUPANCY[0]
MOV AH, 0
CALL PRINT_NUM

LEA DX, MSG_SLASH_CAP
CALL PRINT_STRING

MOV AL, BLOCK_CAPACITY[0]
MOV AH, 0
CALL PRINT_NUM

LEA DX, MSG_OCC_B
CALL PRINT_STRING

MOV AL, BLOCK_OCCUPANCY[1]
MOV AH, 0
CALL PRINT_NUM

LEA DX, MSG_SLASH_CAP
CALL PRINT_STRING

MOV AL, BLOCK_CAPACITY[1]
MOV AH, 0
CALL PRINT_NUM

LEA DX, MSG_OCC_C
CALL PRINT_STRING

MOV AL, BLOCK_OCCUPANCY[2]
MOV AH, 0
CALL PRINT_NUM

LEA DX, MSG_SLASH_CAP
CALL PRINT_STRING

MOV AL, BLOCK_CAPACITY[2]
MOV AH, 0
CALL PRINT_NUM

RET

DISPLAY_BLOCK_OCCUPANCY ENDP

END MAIN
